{
  "name": "Garden",
  "creator": {
    "name": "jehelk",
    "email": " "
  },
  "coreColors": {
    "primaryColor": "#E85656",
    "secondaryColor": "#457345",
    "accentColor": "#A1D4A1"
  },
  "darkColors": {
    "windowButtonIcon": "#A1D4A1",
    "hoveredItemBackground": "rgba(232, 86, 86, 0.6)",
    "selectedItemBackground": "rgba(232, 86, 86, 0.4)",
    "tabText": "#A1D4A1",
    "selectedTabText": "#FFF7F7",
    "mainBackground": "#0B1C1C",
    "headerBackground": "#071212",
    "footerBackground": "#071212",
    "sidePaneBackground": "#0A191A",
    "primaryText": "#FFF7F7",
    "secondaryText": "#A1D4A1",
    "sliderBackground": "#445755",
    "sliderThumbBackground": "#FFF7F7",
    "albumCoverLogo": "#E85656",
    "albumCoverBackground": "#0B080F",
    "headerSeparator": "transparent",
    "paneSeparators": "transparent",
    "settingsSeparators": "#457345",
    "contextMenuSeparators": "#457345",
    "scrollBars": "#457345",
    "searchBox": "#445755",
    "searchBoxText": "#FFF7F7",
    "searchBoxIcon": "#FFF7F7",
    "dialogBackground": "#445755",
    "tooltipText": "#071212",
    "buttonBorder": "#E85656",
    "highlightForeground": "#FFF7F7"
  },

"options": {
    "centerAlbumInfoText": false
  }
}